server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: question-service
          uri: lb://QUESTIONSERVICE  # Use Eureka service ID
          predicates:
            - Path=/api/questions/**
        - id: quiz-service
          uri: lb://QUIZSERVICE  # Use Eureka service ID
          predicates:
            - Path=/api/quiz/**
        - id: frontend
          uri: http://localhost:3000
          predicates:
            - Path=/api/quiz/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka  # Eureka Server URL
  instance:
    hostname: localhost